const fs = require('fs')
const path = require('path')

function w(p, lines) {
  const dir = path.dirname(p)
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true })
  fs.writeFileSync(p, lines.join('\n') + '\n', 'utf8')
  console.log('OK ' + p)
}

// src/lib/firebase.js - Firebase client config
w('src/lib/firebase.js', [
  "import { initializeApp, getApps } from 'firebase/app'",
  "import { getAuth, GoogleAuthProvider } from 'firebase/auth'",
  "",
  "const firebaseConfig = {",
  "  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,",
  "  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,",
  "  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,",
  "  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,",
  "  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,",
  "  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,",
  "}",
  "",
  "const app = getApps().length === 0 ? initializeApp(firebaseConfig) : getApps()[0]",
  "export const auth = getAuth(app)",
  "export const googleProvider = new GoogleAuthProvider()"
])

// src/lib/firebase-admin.js - Firebase Admin for server-side token verification
w('src/lib/firebase-admin.js', [
  "import { initializeApp, getApps, cert } from 'firebase-admin/app'",
  "import { getAuth } from 'firebase-admin/auth'",
  "",
  "if (!getApps().length) {",
  "  initializeApp({",
  "    credential: cert({",
  "      projectId: process.env.FIREBASE_PROJECT_ID,",
  "      clientEmail: process.env.FIREBASE_CLIENT_EMAIL,",
  "      privateKey: process.env.FIREBASE_PRIVATE_KEY?.replace(/\\\\n/g, '\\n'),",
  "    }),",
  "  })",
  "}",
  "",
  "export const adminAuth = getAuth()"
])

// src/lib/auth.js - server-side session verification using Firebase token
w('src/lib/auth.js', [
  "import { adminAuth } from './firebase-admin'",
  "import { cookies } from 'next/headers'",
  "",
  "export async function getSession() {",
  "  try {",
  "    const cookieStore = await cookies()",
  "    const token = cookieStore.get('firebase_token')?.value",
  "    if (!token) return null",
  "    const decoded = await adminAuth.verifyIdToken(token)",
  "    return { userId: decoded.uid, email: decoded.email, name: decoded.name }",
  "  } catch {",
  "    return null",
  "  }",
  "}"
])

// src/app/api/auth/session/route.js - set/clear session cookie
w('src/app/api/auth/session/route.js', [
  "export async function POST(req) {",
  "  const { token } = await req.json()",
  "  const res = Response.json({ success: true })",
  "  if (token) {",
  "    res.headers.set('Set-Cookie', 'firebase_token=' + token + '; Path=/; HttpOnly; SameSite=Lax; Max-Age=3600')",
  "  } else {",
  "    res.headers.set('Set-Cookie', 'firebase_token=; Path=/; HttpOnly; Max-Age=0')",
  "  }",
  "  return res",
  "}"
])

// src/app/api/auth/me/route.js - get current user from DB
w('src/app/api/auth/me/route.js', [
  "import { prisma } from '@/lib/prisma'",
  "import { getSession } from '@/lib/auth'",
  "",
  "export async function GET() {",
  "  try {",
  "    const session = await getSession()",
  "    if (!session) return Response.json({ user: null })",
  "    let user = await prisma.user.findUnique({ where: { firebaseId: session.userId } })",
  "    if (!user) {",
  "      user = await prisma.user.create({",
  "        data: { firebaseId: session.userId, email: session.email || '', name: session.name || '' }",
  "      })",
  "    }",
  "    return Response.json({ user: { id: user.id, email: user.email, name: user.name, plan: user.plan, blogsUsed: user.blogsUsed } })",
  "  } catch {",
  "    return Response.json({ user: null })",
  "  }",
  "}"
])

// src/components/AuthModal.jsx - Firebase auth modal with Google + Email
w('src/components/AuthModal.jsx', [
  "'use client'",
  "import { useState } from 'react'",
  "import { auth, googleProvider } from '@/lib/firebase'",
  "import { signInWithPopup, createUserWithEmailAndPassword, signInWithEmailAndPassword, updateProfile } from 'firebase/auth'",
  "",
  "const inp = { height: 46, padding: '0 14px', borderRadius: 10, background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.1)', color: '#f0f0ff', fontSize: 14, outline: 'none', width: '100%', boxSizing: 'border-box' }",
  "",
  "async function saveSession(user) {",
  "  const token = await user.getIdToken()",
  "  await fetch('/api/auth/session', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ token }) })",
  "  const meRes = await fetch('/api/auth/me')",
  "  const meData = await meRes.json()",
  "  return meData.user",
  "}",
  "",
  "export default function AuthModal({ onClose, onSuccess }) {",
  "  const [mode, setMode] = useState('login')",
  "  const [email, setEmail] = useState('')",
  "  const [password, setPassword] = useState('')",
  "  const [name, setName] = useState('')",
  "  const [error, setError] = useState('')",
  "  const [loading, setLoading] = useState(false)",
  "",
  "  async function handleGoogle() {",
  "    setLoading(true); setError('')",
  "    try {",
  "      const result = await signInWithPopup(auth, googleProvider)",
  "      const dbUser = await saveSession(result.user)",
  "      onSuccess(dbUser)",
  "    } catch (e) { setError(e.message) }",
  "    setLoading(false)",
  "  }",
  "",
  "  async function handleEmail(e) {",
  "    e.preventDefault(); setLoading(true); setError('')",
  "    try {",
  "      let result",
  "      if (mode === 'signup') {",
  "        result = await createUserWithEmailAndPassword(auth, email, password)",
  "        if (name) await updateProfile(result.user, { displayName: name })",
  "      } else {",
  "        result = await signInWithEmailAndPassword(auth, email, password)",
  "      }",
  "      const dbUser = await saveSession(result.user)",
  "      onSuccess(dbUser)",
  "    } catch (e) {",
  "      const msg = e.code === 'auth/email-already-in-use' ? 'Email already registered' :",
  "        e.code === 'auth/wrong-password' || e.code === 'auth/user-not-found' ? 'Invalid email or password' :",
  "        e.code === 'auth/weak-password' ? 'Password must be at least 6 characters' : e.message",
  "      setError(msg)",
  "    }",
  "    setLoading(false)",
  "  }",
  "",
  "  return (",
  "    <div style={{ position: 'fixed', inset: 0, zIndex: 1000, display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'rgba(0,0,0,0.75)', backdropFilter: 'blur(6px)' }}>",
  "      <div style={{ background: '#0f0f1a', border: '1px solid rgba(255,255,255,0.08)', borderRadius: 20, padding: 36, width: '100%', maxWidth: 420, position: 'relative' }}>",
  "        <button onClick={onClose} style={{ position: 'absolute', top: 16, right: 16, background: 'none', border: 'none', color: '#9090a8', fontSize: 20, cursor: 'pointer' }}>✕</button>",
  "        <div style={{ textAlign: 'center', marginBottom: 24 }}>",
  "          <div style={{ width: 44, height: 44, borderRadius: 12, background: 'linear-gradient(135deg,#7c3aed,#a855f7)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 22, margin: '0 auto 12px' }}>✍</div>",
  "          <h2 style={{ color: '#f0f0ff', fontSize: 22, fontWeight: 800, margin: 0 }}>{mode === 'login' ? 'Welcome back' : 'Create account'}</h2>",
  "          <p style={{ color: '#9090a8', fontSize: 14, marginTop: 6 }}>{mode === 'login' ? 'Sign in to generate blogs' : 'Start writing SEO blogs today'}</p>",
  "        </div>",
  "",
  "        <button onClick={handleGoogle} disabled={loading} style={{ width: '100%', height: 46, borderRadius: 10, border: '1px solid rgba(255,255,255,0.15)', background: 'rgba(255,255,255,0.05)', color: '#f0f0ff', fontSize: 14, fontWeight: 600, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 10, marginBottom: 16 }}>",
  "          <svg width='18' height='18' viewBox='0 0 24 24'><path fill='#4285F4' d='M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z'/><path fill='#34A853' d='M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z'/><path fill='#FBBC05' d='M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l3.66-2.84z'/><path fill='#EA4335' d='M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z'/></svg>",
  "          Continue with Google",
  "        </button>",
  "",
  "        <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 16 }}>",
  "          <div style={{ flex: 1, height: 1, background: 'rgba(255,255,255,0.08)' }} />",
  "          <span style={{ color: '#9090a8', fontSize: 12 }}>or</span>",
  "          <div style={{ flex: 1, height: 1, background: 'rgba(255,255,255,0.08)' }} />",
  "        </div>",
  "",
  "        <form onSubmit={handleEmail} style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>",
  "          {mode === 'signup' && <input placeholder='Your name (optional)' value={name} onChange={e => setName(e.target.value)} style={inp} />}",
  "          <input type='email' placeholder='Email address' value={email} onChange={e => setEmail(e.target.value)} required style={inp} />",
  "          <input type='password' placeholder='Password' value={password} onChange={e => setPassword(e.target.value)} required style={inp} />",
  "          {error && <div style={{ padding: '10px 14px', borderRadius: 10, background: 'rgba(255,80,80,0.1)', border: '1px solid rgba(255,80,80,0.2)', color: '#ff8080', fontSize: 13 }}>{error}</div>}",
  "          <button type='submit' disabled={loading} style={{ height: 48, borderRadius: 12, border: 'none', background: 'linear-gradient(135deg,#7c3aed,#a855f7)', color: '#fff', fontSize: 15, fontWeight: 700, cursor: loading ? 'not-allowed' : 'pointer', opacity: loading ? 0.7 : 1 }}>",
  "            {loading ? 'Please wait...' : mode === 'login' ? 'Sign In' : 'Create Account'}",
  "          </button>",
  "        </form>",
  "",
  "        <div style={{ textAlign: 'center', marginTop: 20, fontSize: 14, color: '#9090a8' }}>",
  "          {mode === 'login' ? \"Don't have an account? \" : 'Already have an account? '}",
  "          <button onClick={() => { setMode(mode === 'login' ? 'signup' : 'login'); setError('') }} style={{ background: 'none', border: 'none', color: '#8b5cf6', cursor: 'pointer', fontWeight: 600 }}>",
  "            {mode === 'login' ? 'Sign up free' : 'Sign in'}",
  "          </button>",
  "        </div>",
  "      </div>",
  "    </div>",
  "  )",
  "}"
])

// src/components/Header.jsx - updated for Firebase
w('src/components/Header.jsx', [
  "'use client'",
  "import { useState } from 'react'",
  "import { auth } from '@/lib/firebase'",
  "import { signOut } from 'firebase/auth'",
  "import AuthModal from './AuthModal'",
  "",
  "export default function Header({ user, onAuthChange }) {",
  "  const [showAuth, setShowAuth] = useState(false)",
  "",
  "  async function logout() {",
  "    await signOut(auth)",
  "    await fetch('/api/auth/session', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ token: null }) })",
  "    onAuthChange(null)",
  "  }",
  "",
  "  return (",
  "    <>",
  "      <header style={{ position: 'sticky', top: 0, zIndex: 100, background: 'rgba(7,7,15,0.94)', backdropFilter: 'blur(14px)', borderBottom: '1px solid rgba(255,255,255,0.08)' }}>",
  "        <div style={{ maxWidth: 960, margin: '0 auto', padding: '16px 20px', display: 'flex', alignItems: 'center', gap: 12 }}>",
  "          <a href='/' style={{ display: 'flex', alignItems: 'center', gap: 10, textDecoration: 'none' }}>",
  "            <div style={{ width: 32, height: 32, borderRadius: 10, background: 'linear-gradient(135deg,#7c3aed,#a855f7)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 18 }}>✍</div>",
  "            <div style={{ lineHeight: 1.1 }}>",
  "              <div style={{ fontWeight: 900, fontSize: 18, color: '#f0f0ff' }}><span style={{ color: '#8b5cf6' }}>SEO</span> <span style={{ fontWeight: 500, fontSize: 16, color: '#a0a0b0' }}>Blog Writer</span></div>",
  "              <div style={{ fontSize: 11, color: 'rgba(255,255,255,0.2)', letterSpacing: 0.8 }}>AI-powered content in minutes</div>",
  "            </div>",
  "          </a>",
  "          <div style={{ marginLeft: 'auto', display: 'flex', alignItems: 'center', gap: 10 }}>",
  "            {user ? (",
  "              <>",
  "                <a href='/dashboard' style={{ padding: '8px 16px', borderRadius: 8, border: '1px solid rgba(255,255,255,0.1)', background: 'rgba(255,255,255,0.04)', color: '#f0f0ff', textDecoration: 'none', fontSize: 13 }}>Dashboard</a>",
  "                <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '6px 12px', borderRadius: 8, background: 'rgba(139,92,246,0.1)', border: '1px solid rgba(139,92,246,0.2)' }}>",
  "                  <div style={{ width: 24, height: 24, borderRadius: '50%', background: 'linear-gradient(135deg,#7c3aed,#a855f7)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 11, color: '#fff', fontWeight: 700 }}>",
  "                    {user.email?.[0]?.toUpperCase()}",
  "                  </div>",
  "                  <span style={{ fontSize: 13, color: '#a78bfa' }}>{user.name || user.email?.split('@')[0]}</span>",
  "                  <span style={{ fontSize: 11, color: 'rgba(255,255,255,0.3)', background: 'rgba(255,255,255,0.06)', padding: '2px 7px', borderRadius: 20 }}>{user.plan}</span>",
  "                </div>",
  "                <button onClick={logout} style={{ padding: '8px 14px', borderRadius: 8, border: '1px solid rgba(255,80,80,0.2)', background: 'rgba(255,80,80,0.06)', color: '#ff8080', cursor: 'pointer', fontSize: 13 }}>Logout</button>",
  "              </>",
  "            ) : (",
  "              <>",
  "                <button onClick={() => setShowAuth(true)} style={{ padding: '8px 18px', borderRadius: 8, border: '1px solid rgba(255,255,255,0.15)', background: 'transparent', color: '#f0f0ff', cursor: 'pointer', fontSize: 13 }}>Sign In</button>",
  "                <button onClick={() => setShowAuth(true)} style={{ padding: '8px 18px', borderRadius: 8, border: 'none', background: 'linear-gradient(135deg,#7c3aed,#a855f7)', color: '#fff', cursor: 'pointer', fontSize: 13, fontWeight: 700 }}>Sign Up Free</button>",
  "              </>",
  "            )}",
  "          </div>",
  "        </div>",
  "      </header>",
  "      {showAuth && <AuthModal onClose={() => setShowAuth(false)} onSuccess={(u) => { onAuthChange(u); setShowAuth(false) }} />}",
  "    </>",
  "  )",
  "}"
])

// Update generate route to use firebaseId
w('src/app/api/generate/route.js', [
  "import OpenAI from 'openai'",
  "import { prisma } from '@/lib/prisma'",
  "import { getSession } from '@/lib/auth'",
  "export const maxDuration = 300",
  "export const dynamic = 'force-dynamic'",
  "const grok = new OpenAI({ apiKey: process.env.GROK_API_KEY, baseURL: 'https://api.groq.com/openai/v1' })",
  "const FC = process.env.FIRECRAWL_API_KEY",
  "async function ask(system, user, maxTokens) {",
  "  const res = await grok.chat.completions.create({ model: 'llama-3.3-70b-versatile', max_tokens: maxTokens || 2000, messages: [{ role: 'system', content: system }, { role: 'user', content: user }] })",
  "  return res.choices[0].message.content",
  "}",
  "function safeJson(raw) {",
  "  const c = raw.replace(/```json/g, '').replace(/```/g, '').trim()",
  "  const m = c.match(/(\\{[\\s\\S]*\\}|\\[[\\s\\S]*\\])/)",
  "  try { return JSON.parse(m ? m[0] : c) } catch { throw new Error('Bad JSON: ' + raw.substring(0, 200)) }",
  "}",
  "async function fcSearch(query, limit) {",
  "  const res = await fetch('https://api.firecrawl.dev/v1/search', { method: 'POST', headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + FC }, body: JSON.stringify({ query, limit: limit || 10, scrapeOptions: { formats: ['markdown'] } }) })",
  "  if (!res.ok) throw new Error('Firecrawl failed: ' + res.status)",
  "  const d = await res.json(); return d.data || []",
  "}",
  "async function fcScrape(url) {",
  "  try {",
  "    const res = await fetch('https://api.firecrawl.dev/v1/scrape', { method: 'POST', headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + FC }, body: JSON.stringify({ url, formats: ['markdown'], onlyMainContent: true }) })",
  "    if (!res.ok) return null",
  "    const d = await res.json(); return d.data && d.data.markdown ? d.data.markdown : null",
  "  } catch { return null }",
  "}",
  "export async function POST(req) {",
  "  const session = await getSession()",
  "  if (!session) return new Response('Unauthorized', { status: 401 })",
  "  const body = await req.json()",
  "  const topic = body.topic",
  "  const intent = body.commercialIntent || 'informational'",
  "  const enc = new TextEncoder()",
  "  const stream = new ReadableStream({",
  "    async start(ctrl) {",
  "      function send(event, data) { ctrl.enqueue(enc.encode('data: ' + JSON.stringify({ event, data }) + '\\n\\n')) }",
  "      try {",
  "        let user = await prisma.user.findUnique({ where: { firebaseId: session.userId } })",
  "        if (!user) user = await prisma.user.create({ data: { firebaseId: session.userId, email: session.email || '', name: session.name || '' } })",
  "        if (user.plan === 'free' && user.blogsUsed >= 2) { send('error', { message: 'Free plan limit reached. Upgrade to Pro.' }); ctrl.close(); return }",
  "        send('step', { id: 'keywords', status: 'active', msg: 'Researching keywords...' })",
  "        const topicSerp = await fcSearch(topic, 6)",
  "        const serpBrief = topicSerp.slice(0, 6).map((r, i) => (i+1) + '. ' + ((r.metadata && r.metadata.title) || 'Untitled') + '\\n' + (r.markdown || r.content || '').replace(/\\s+/g, ' ').substring(0, 200)).join('\\n\\n')",
  "        const kw = safeJson(await ask('SEO expert. Respond ONLY valid JSON, no markdown.', 'Topic: ' + topic + '\\nIntent: ' + intent + '\\nSERP:\\n' + serpBrief + '\\nReturn: {\"primaryKeyword\":\"4-6 word keyword\",\"secondaryKeywords\":[\"kw1\",\"kw2\",\"kw3\",\"kw4\"]}', 300))",
  "        send('data', { primaryKeyword: kw.primaryKeyword, secondaryKeywords: kw.secondaryKeywords })",
  "        send('step', { id: 'keywords', status: 'done' })",
  "        send('step', { id: 'meta', status: 'active', msg: 'Writing meta data...' })",
  "        const meta = safeJson(await ask('SEO copywriter. Respond ONLY valid JSON, no markdown.', 'Keyword: ' + kw.primaryKeyword + '\\nTopic: ' + topic + '\\nReturn: {\"metaTitle\":\"50-60 chars\",\"metaDescription\":\"140-155 chars\",\"permalink\":\"3-5-word-slug\"}', 400))",
  "        send('data', { metaTitle: meta.metaTitle, metaDescription: meta.metaDescription, permalink: meta.permalink })",
  "        send('step', { id: 'meta', status: 'done' })",
  "        send('step', { id: 'serp', status: 'active', msg: 'Searching SERP...' })",
  "        const serpResults = await fcSearch(kw.primaryKeyword, 10)",
  "        send('step', { id: 'scraping', status: 'active', msg: 'Scraping top 10 pages...' })",
  "        const pages = []",
  "        for (let i = 0; i < Math.min(serpResults.length, 10); i++) {",
  "          const r = serpResults[i]",
  "          const url = r.url || (r.metadata && r.metadata.sourceURL)",
  "          const title = (r.metadata && r.metadata.title) || r.title || url",
  "          send('step', { id: 'scraping', status: 'active', msg: 'Scraping ' + (i+1) + '/10: ' + String(title).substring(0, 40) })",
  "          let content = r.markdown || r.content || ''",
  "          if (!content && url) content = (await fcScrape(url)) || ''",
  "          pages.push({ rank: i+1, title, url, content: content.substring(0, 3000) })",
  "        }",
  "        const serpSummary = pages.map(p => ({ rank: p.rank, title: p.title, url: p.url, snippet: p.content.substring(0, 400) }))",
  "        send('data', { serpData: { results: serpSummary } })",
  "        send('step', { id: 'serp', status: 'done' })",
  "        send('step', { id: 'scraping', status: 'done' })",
  "        send('step', { id: 'semantic', status: 'active', msg: 'Extracting semantic keywords...' })",
  "        const combined = pages.map(p => p.content).join(' ').substring(0, 6000)",
  "        const sem = safeJson(await ask('NLP expert. Respond ONLY valid JSON, no markdown.', 'Keyword: ' + kw.primaryKeyword + '\\nContent:\\n' + combined + '\\nReturn: {\"semanticKeywords\":[\"kw1\",\"kw2\"]}', 600))",
  "        send('data', { semanticKeywords: sem.semanticKeywords })",
  "        send('step', { id: 'semantic', status: 'done' })",
  "        send('step', { id: 'structure', status: 'active', msg: 'Planning blog structure...' })",
  "        const angles = pages.slice(0, 5).map(p => 'Rank ' + p.rank + ': ' + p.content.substring(0, 250)).join('\\n\\n')",
  "        const struct = safeJson(await ask('SEO strategist. Respond ONLY valid JSON, no markdown.', 'Keyword: ' + kw.primaryKeyword + '\\nTitle: ' + meta.metaTitle + '\\nIntent: ' + intent + '\\nCompetitors:\\n' + angles + '\\n10 sections: 1=intro,2-7=body,8=conclusion,9=cta,10=faq\\nReturn: {\"sections\":[{\"num\":1,\"h2\":\"...\",\"h3s\":[\"...\"],\"angle\":\"...\",\"type\":\"intro\"}]}', 1800))",
  "        send('data', { structure: struct.sections })",
  "        send('step', { id: 'structure', status: 'done' })",
  "        send('step', { id: 'writing', status: 'active', msg: 'Writing blog sections...' })",
  "        const allSections = []",
  "        const refContent = pages.map(p => p.content.substring(0, 500)).join('\\n---\\n').substring(0, 5000)",
  "        for (let j = 0; j < struct.sections.length; j++) {",
  "          const sec = struct.sections[j]",
  "          send('section_start', { index: j, h2: sec.h2 })",
  "          send('step', { id: 'writing', status: 'active', msg: 'Writing ' + (j+1) + '/10: ' + String(sec.h2).substring(0, 40) })",
  "          const h3s = (sec.h3s || []).map(h => '### ' + h).join('\\n')",
  "          const isFaq = String(sec.type).toLowerCase().indexOf('faq') > -1",
  "          const isCta = String(sec.type).toLowerCase().indexOf('cta') > -1",
  "          let prompt = 'Write EXACTLY 400 words.\\nTitle: ' + meta.metaTitle + '\\nKeyword: ' + kw.primaryKeyword + '\\nRef: ' + refContent.substring(0, 1000) + '\\nSECTION:\\n## ' + sec.h2 + '\\n' + h3s + '\\nAngle: ' + (sec.angle || 'practical') + '\\nRules: 400 words, include headings, first person I, short paragraphs'",
  "          if (isFaq) prompt += '\\nFAQ: 6 questions as ### headings, 50-70 words each'",
  "          if (isCta) prompt += '\\nCTA: persuasive, personal, clear action'",
  "          const secContent = await ask('World-class SEO writer. Simple English, first person I, E-E-A-T.', prompt, 950)",
  "          allSections.push(secContent)",
  "          send('section_done', { index: j, content: secContent })",
  "        }",
  "        send('step', { id: 'writing', status: 'done' })",
  "        send('step', { id: 'grammar', status: 'active', msg: 'Grammar check...' })",
  "        const polished = await ask('Professional editor. Fix only errors. Return full markdown.', 'Fix grammar, typos, awkward sentences, unnecessary commas/dashes. Keep first person I.\\nBLOG:\\n' + allSections.join('\\n\\n'), 6000)",
  "        send('data', { finalBlog: polished })",
  "        send('step', { id: 'grammar', status: 'done' })",
  "        send('step', { id: 'detection', status: 'active', msg: 'Checking AI likelihood...' })",
  "        const detect = safeJson(await ask('Content auditor. Respond ONLY valid JSON, no markdown.', 'Return: {\"aiLikelihoodPercent\":0,\"plagiarismRiskPercent\":0,\"reasons\":[],\"riskySentences\":[]}\\nBLOG:\\n' + polished.substring(0, 8000), 600))",
  "        send('data', { aiLikelihoodPercent: detect.aiLikelihoodPercent, plagiarismRiskPercent: detect.plagiarismRiskPercent, qualityReasons: detect.reasons })",
  "        send('step', { id: 'detection', status: 'done' })",
  "        send('step', { id: 'image', status: 'active', msg: 'Generating cover image...' })",
  "        const imgRaw = await ask('Creative director. One image prompt only, no quotes, 50-100 words.', 'Cover 16:9 for: ' + meta.metaTitle + '. Modern, professional, no text overlays.', 200)",
  "        const imgPrompt = imgRaw.trim().replace(/\"/g, '')",
  "        const coverImageUrl = 'https://image.pollinations.ai/prompt/' + encodeURIComponent(imgPrompt) + '?width=1200&height=675&nologo=true'",
  "        send('data', { coverImageUrl, imagePrompt: imgPrompt })",
  "        send('step', { id: 'image', status: 'done' })",
  "        await prisma.blog.create({ data: { userId: user.id, topic, primaryKeyword: kw.primaryKeyword, secondaryKeywords: kw.secondaryKeywords, metaTitle: meta.metaTitle, metaDescription: meta.metaDescription, permalink: meta.permalink, semanticKeywords: sem.semanticKeywords || [], serpData: { results: serpSummary }, structure: struct.sections, finalBlog: polished, coverImageUrl, imagePrompt: imgPrompt, aiLikelihood: detect.aiLikelihoodPercent, plagiarismRisk: detect.plagiarismRiskPercent, qualityReasons: detect.reasons || [] } })",
  "        await prisma.user.update({ where: { id: user.id }, data: { blogsUsed: { increment: 1 } } })",
  "        send('done', { success: true })",
  "      } catch (err) {",
  "        console.error(err)",
  "        send('error', { message: err.message || 'Something went wrong.' })",
  "      }",
  "      ctrl.close()",
  "    }",
  "  })",
  "  return new Response(stream, { headers: { 'Content-Type': 'text/event-stream', 'Cache-Control': 'no-cache', 'Connection': 'keep-alive' } })",
  "}"
])

console.log('\nAll Firebase files written!')
console.log('\nNEXT STEPS:')
console.log('1. npm install firebase firebase-admin')
console.log('2. Go to https://console.firebase.google.com')
console.log('3. Create project -> Enable Authentication -> Email/Password + Google')
console.log('4. Project Settings -> Your apps -> Web app -> copy config')
console.log('5. Project Settings -> Service accounts -> Generate new private key')
console.log('6. Add to .env.local (see instructions below)')
console.log('7. npx prisma migrate dev --name firebase-auth')
console.log('8. npm run dev')
